### ISSUE TITLE
Missing files

### ISSUE THREAD

**Issue by juergengaor** [romanoide/tumblrwave#1]
Hi Romanoide,
I've noticed that at least the following files/directories are missing from the repository's master branch:
"public/src/image", used by the 'copy-images' task in the gulpfile;
"public/src/fonts", used by the 'copy-fonts' task.
I ran the server locally and the browser returned this:
![screen](https://cloud.githubusercontent.com/assets/11914641/7107294/b8ae0a1e-e126-11e4-8a8d-81e05faad448.png)
Regards!

**Comment by romanoide** [comment]
Thanks, I've fixed the issue in tha latest update
